Repository ministryofjustice/laa-assure-hmrc-data, pull requests merged in 2023-06, with the labels that each got.

#233 ap-4166: use short-lived ecr credentials in test-build-deploy workflow
  .github/actions/build_and_push/action.yml
  .github/actions/deploy/action.yml
  .github/actions/deploy_branch/action.yml
  .github/workflows/test-build-deploy.yml
Labels: ready for review

#286 AP-4181: Add "Clients NI contributions from employment" field to results
  app/models/concerns/hmrc_interface_resultable.rb
  app/services/submission_result_csv.rb
  lib/extensions/array_extension.rb
  spec/factories/submissions.rb
  spec/fixtures/files/results/hmrc_interface_successful_result_response_body_with_income_paye.json
  spec/models/concerns/hmrc_interface_resultable_spec.rb
  spec/services/bulk_submission_result_writer_service_spec.rb
  spec/services/submission_result_csv_spec.rb
Labels: ready for review

#280 ap-4122: add purge_worker job
  app/workers/purge_sensitive_data_worker.rb
  config/sidekiq.yml
  spec/rails_helper.rb
  spec/workers/purge_sensitive_data_worker_spec.rb
Labels: ready for review

#294 AP-4181: Add "Client's Income from Self Employment" to result file
  app/models/concerns/hmrc_interface_resultable.rb
  app/services/submission_result_csv.rb
  spec/factories/submissions.rb
  spec/fixtures/files/results/hmrc_interface_successful_result_response_body_with_self_assessment_summary.json
  spec/models/concerns/hmrc_interface_resultable_spec.rb
  spec/services/bulk_submission_result_writer_service_spec.rb
  spec/services/submission_result_csv_spec.rb
Labels: ready for review

#234 AP-4158: virus-scanning
  .env.sample
  .github/workflows/test-build-deploy.yml
  .helm/assure-hmrc-data/templates/deployment-web.yaml
  .rubocop.yml
  Dockerfile
  README.md
  app/controllers/bulk_submission_forms_controller.rb
  app/forms/bulk_submission_form.rb
  app/forms/concerns/malware_scanning.rb
  app/models/malware_scan_result.rb
  app/services/malware_scanner.rb
  bin/install_clamav_on_mac
  bin/setup
  config/application.rb
  config/clamd.container.conf
  config/locales/en/models/bulk_submissions.yml
  db/migrate/20230607074210_create_malware_scan_results.rb
  db/schema.rb
  docker-compose.yml
  docs/development/setup.md
  docs/development/virus_scanning.md
  spec/fixtures/files/malware.doc
  spec/forms/bulk_submission_form_spec.rb
  spec/requests/bulk_submission_forms_controller_spec.rb
  spec/services/malware_scanner_spec.rb
  spec/support/malware_scanner.rb
  spec/system/bulk_submission_form_dropzone_spec.rb
Labels: ready for review, security

#317 Add malware.csv file
  spec/fixtures/files/malware.csv
  spec/fixtures/files/malware.doc
  spec/forms/bulk_submission_form_spec.rb
  spec/requests/bulk_submission_forms_controller_spec.rb
  spec/services/malware_scanner_spec.rb
Labels: ready for review, security

#334 Enable content security policy
  config/initializers/content_security_policy.rb
Labels: approved

#332 Make session cookie store secure
  config/initializers/session_store.rb
Labels: approved

#333 Make FE assets performant
  package.json
Labels: approved

#327 ap-4168: log user that downloads bulk submission results file
  app/controllers/bulk_submissions_controller.rb
  app/views/bulk_submissions/index.html.erb
  app/views/bulk_submissions/show.html.erb
  config/application.rb
  config/initializers/sidekiq.rb
  config/routes.rb
  spec/requests/bulk_submissions_controller_spec.rb
Labels: ready for review
