Repository ministryofjustice/laa-assure-hmrc-data, pull requests merged in 2025-01, with the labels that each got.

#1479 Fix: Update gemfile platforms
  Gemfile.lock
Labels: ready for review

#1477 AP-5659: Bump ruby 3.3.6 to 3.4.1
  .ruby-version
  Dockerfile
  Gemfile
  Gemfile.lock
  docs/development/setup.md
  spec/lib/rails_host_spec.rb
Labels: approved

#1480 Chore: bump bundler 2.5.11 to 2.6.2
  Gemfile.lock
Labels: ready for review

#1481 AP-5667: Bump rails 7.2.2.1 to 8.0.1
  Gemfile
  Gemfile.lock
  bin/rubocop
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/assets.rb
  config/initializers/cors.rb
  config/initializers/filter_parameter_logging.rb
  config/puma.rb
Labels: approved, UAT

#1482 Chore: Amend /healthcheck endpoint to use database_exists?
  app/controllers/status_controller.rb
  spec/requests/status_controller_spec.rb
Labels: ready for review

#1483 Fix: Update dependabot after Rails upgrade
  .github/dependabot.yml
Labels: ready for review

#1485 Chore: Add build steps for dependabot PRs
  .github/workflows/test-build-deploy.yml
Labels: ready for review
